name: Test Tcpdump Ubuntu
on:
  - push
jobs:
  test:
    name: Test Tcpdump Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Test curl
      run: |
        sudo tcpdump -i eth0 -s 65535 -w githubactions.cap host 193.60.236.19 &
        curl https://join.osmfoundation.org/xmlrpc.php
        curl https://join.osmfoundation.org/xmlrpc.php
    - name: Tcpdump full
      if: ${{ always() }}
      run: |
        sudo killall tcpdump
        sudo cat githubactions.cap | gzip -9 | base64
