name: Test Tcpdump Ubuntu
on:
  - push
jobs:
  test:
    name: Test Tcpdump Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Test curl
      run: |
        set +e
        curl icanhazip.com
        sudo tcpdump -i eth0 -s 65535 -w githubactions-ubuntu.pcap &
        curl --silent --show-error https://join.osmfoundation.org/xmlrpc.php
        curl --silent --show-error https://git.openstreetmap.org/
        curl --silent --show-error https://join.osmfoundation.org/xmlrpc.php
        sudo killall -2 tcpdump
    - name: Upload tcpdump
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: githubactions-ubuntu
        path: githubactions-ubuntu.pcap