name: Test Tcpdump Ubuntu
on:
  - push
jobs:
  test:
    name: Test Tcpdump Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Test curl
      run: |
        sudo tcpdump -i eth0 -s 65535 -w githubactions-ubuntu.pcap host 193.60.236.19 &
        curl --local-port 40114 https://join.osmfoundation.org/xmlrpc.php
        curl --local-port 40115 https://join.osmfoundation.org/xmlrpc.php
    - name: Tcpdump kill
      if: ${{ always() }}
      run: |
        sudo killall -2 tcpdump    - name: Upload tcpdump
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: githubactions-ubuntu
        path: githubactions-ubuntu.pcap