name: Test Tcpdump Ubuntu
on:
  - push
jobs:
  test:
    name: Test Tcpdump Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Test curl
      run: |
        set +e
        set -x
        curl --silent icanhazip.com
        sudo tcpdump -i eth0 -s 65535 -w githubactions-ubuntu.pcap host 193.60.236.19 &
        curl --silent --show-error https://join.osmfoundation.org/
        curl --silent --show-error https://join.osmfoundation.org/
        sudo killall -2 tcpdump
        sleep 1
    - name: Upload tcpdump
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: githubactions-ubuntu
        path: githubactions-ubuntu.pcap
    - name: Always fail so I can conveniently re-run
      if: ${{ always() }}
      run: |
        exit 99
