name: Test Tcpdump macOS
on:
  - push
jobs:
  test:
    name: Test Tcpdump macOS
    runs-on: macos-latest
    steps:
    - name: Test curl
      run: |
        sudo ip addr
        sudo tcpdump -i eth0 -s 65535 -w githubactions.cap host 193.60.236.19 &
        curl https://join.osmfoundation.org/xmlrpc.php
        curl https://join.osmfoundation.org/xmlrpc.php
    - name: Tcpdump full
      if: ${{ always() }}
      run: |
        sudo killall tcpdump
        sudo cat githubactions.cap | gzip -9 | base64
