name: Test Tcpdump macOS
on:
  - push
jobs:
  test:
    name: Test Tcpdump macOS
    runs-on: macos-latest
    steps:
    - name: Test curl
      run: |
        sudo tcpdump -i en0 -s 65535 -w githubactions-macos.pcap host 193.60.236.19 &
        curl --local-port 40114 https://join.osmfoundation.org/xmlrpc.php
        curl --local-port 40115 https://join.osmfoundation.org/xmlrpc.php
    - name: Tcpdump kill
      if: ${{ always() }}
      run: |
        sudo killall tcpdump
    - name: Upload tcpdump
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: githubactions-macos
        path: githubactions-macos.pcap
