name: Test Kitchen
on:
  - push
jobs:
  test:
    name: Test Kitchen
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup ruby
      uses: actions/setup-ruby@v1
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ runner.OS }}-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundle-${{ runner.OS }}-
    - name: Install gems
      run: |
        gem install bundler
        bundle config set deployment true
        bundle install --jobs 4 --retry 3
    - name: Run kitchen test test-ubuntu-1804
      run: bundle exec kitchen test test-ubuntu-1804
